name: 'XMPP Interoperability Tests'
description: 'Verifies functional behavior of an XMPP server by executing interoperability tests.'
inputs:
  ipAddress:
    description: 'The IP address of the server under test'
    required: true
    default: '127.0.0.1'
  domain:
    description: 'XMPP domain name of server under test'
    required: true
    default: 'example.org'
  timeout:
    description: 'Amount of milliseconds after which an XMPP action (typically an IQ request) is considered timed out.'
    required: false
    default: '5000'
  adminAccountUsername:
    description: 'Account name of a pre-existing user that is allowed to create other users, per XEP-0133. If not provided, In-band registration (XEP-0077) will be used.'
    required: false
  adminAccountPassword:
    description: 'Password for the admin account.'
    required: false
  disabledSpecifications:
    description: 'Comma-separated list of specifications for which tests are to be skipped (eg: "XEP-0045,XEP-0060")'
    required: false
  disabledTests:
    description: 'Comma-separated list of tests that are to be skipped (eg: "EntityCapsTest,SoftwareInfoIntegrationTest")'
    required: false
  logDir:
    description: 'The directory in which the test output and logs are to be stored. This directory will be created, if it does not already exist.'
    required: false
    default: './output'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: zulu

    - uses: dsaltares/fetch-gh-release-asset@1.1.1
      with:
        repo: 'XMPP-Interop-Testing/smack-sint-server-extensions'
        version: 'tags/v1.2'
        file: 'smack-sint-server-extensions-1.2-jar-with-dependencies.jar'

    - run: |
        sudo echo "${{ inputs.ipAddress }} ${{ inputs.domain }}" | sudo tee -a /etc/hosts
        java \
          -Dsinttest.service="${{ inputs.domain }}" \
          -Dsinttest.securityMode=disabled \
          -Dsinttest.replyTimeout=${{ inputs.timeout }} \
          -Dsinttest.adminAccountUsername="${{ inputs.adminAccountUsername }}" \
          -Dsinttest.adminAccountPassword="${{ inputs.adminAccountPassword }}" \
          -Dsinttest.enabledConnections=tcp \
          -Dsinttest.dnsResolver=javax \
          -Dsinttest.disabledSpecifications="${{ inputs.disabledSpecifications }}" \
          -Dsinttest.disabledTests="${{ inputs.disabledTests }}" \
          -Dsinttest.testRunResultProcessors=org.igniterealtime.smack.inttest.SmackIntegrationTestFramework\$JulTestRunResultProcessor,org.igniterealtime.smack.inttest.util.JUnitXmlTestRunResultProcessor \
          -Dsinttest.debugger="org.igniterealtime.smack.inttest.util.FileLoggerFactory" \
          -DlogDir="${{ inputs.logDir }}" \
          -jar smack-sint-server-extensions-1.2-jar-with-dependencies.jar
      shell: bash

    - name: Upload XMPP debug logs as an artifact
      if: always() # Especially when the tests fail, it's desirable to have access to these reports!
      uses: actions/upload-artifact@v4
      with:
        name: XMPP debug logs
        path: '${{ inputs.logDir }}'

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      if: always() # always run even if the previous step fails
      with:
        report_paths: '${{ inputs.logDir }}/test-results.xml'
        suite_regex: '*'
        include_passed: true
        detailed_summary: true
        annotate_only: true