name: Trigger Release from Upstream

on:
  repository_dispatch:
    types: [trigger-workflow]

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version parameters
        id: version
        run: |
            VERSION=${{ github.event.client_payload.version }}
            FILE_VERSION=${VERSION:1} # Strip leading 'v'
            echo "Version: $VERSION"
            echo "File version: $FILE_VERSION"
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "file_version=$FILE_VERSION" >> $GITHUB_OUTPUT
        shell: bash

      - name: Replace the version in the action.yml file
        run: |
            VERSION=${{ github.event.client_payload.version }}
            FILE_VERSION=${VERSION:1} # Strip leading 'v'
            sed -i "s/version: 'tags/.*'/version: '${{ steps.version.outputs.version }}'/" action.yml
            sed -i "s/file: 'smack-sint-server-extensions-.*-jar-with-dependencies.jar'/file: 'smack-sint-server-extensions-${{ steps.version.outputs.file_version }}-jar-with-dependencies.jar'/" action.yml
        shell: bash

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7.0.5
        with:
            commit-message: "Update version to ${{ steps.version.outputs.version }}"
            branch: "update-version-${{ steps.version.outputs.file_version }}"
            title: "Update version to ${{ steps.version.outputs.version }}"
            body: |
                This PR updates the version to ${{ steps.version.outputs.version }}.

                Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)
    